### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by ghost** [nospaceships/raw-socket-sniffer#6]
Hello,

I am not workstation admin and as soon as I launch the script with the proper arguments, I'm getting flooded by the following error : 

```
Exception calling "BlockCopy" with "5" argument(s): "Offset and length were out of bounds for the array or count is
greater than the number of elements from index to the end of the source collection."
At C:\Users\x\test\raw-socket-sniffer.ps1:103 char:5
+     [Buffer]::BlockCopy([BitConverter]::GetBytes($rc), 0, $buffer, 12 ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

You cannot call a method on a null-valued expression.
```

Any idea what could cause this ?

**Comment by stephenwvickers** [comment]
Hi @flacostec 

What version of Windows are you running this on?

Stev

**Comment by ghost** [comment]
Currently running Windows 10 1703 (15036.1324) and I am not administrator of the workstation (I've edited my answer).

**Comment by stephenwvickers** [comment]
Ah okay, so raw sockets on WIndows require administrator privileges (there's a note on [this][1] page).

Can you try using "Run as Administrator"?  Just verified and it worked for me.

Steve

[1]: https://docs.microsoft.com/en-us/windows/desktop/winsock/tcp-ip-raw-sockets-2

**Comment by ghost** [comment]
Worked fine with admin right. :-)

**Comment by GirkovArpa** [comment]
I have the same issue and running as Administrator with Admin PowerShell doesn't solve it.
